/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

/**
 *
 * @author Adalberto Gomez
 */
public class ModalNumeracion extends javax.swing.JDialog {

    /**
     * Creates new form Numeracion
     */
    public ModalNumeracion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbImprimible = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        spnConsecutivo = new javax.swing.JSpinner();
        btnGuardarConsecutivo = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtPrefijo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnCancelarImprimible = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Numeración");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(320, 190));
        setMinimumSize(new java.awt.Dimension(320, 190));
        setPreferredSize(new java.awt.Dimension(320, 190));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        getContentPane().add(cmbImprimible, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 27, 216, -1));

        jLabel1.setText("Formato");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 30, -1, -1));

        spnConsecutivo.setModel(new javax.swing.SpinnerNumberModel(0, 0, 0, 1));
        getContentPane().add(spnConsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 66, 95, -1));

        btnGuardarConsecutivo.setText("Guardar");
        btnGuardarConsecutivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarConsecutivoActionPerformed(evt);
            }
        });
        getContentPane().add(btnGuardarConsecutivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, -1, -1));

        jLabel2.setText("Prefijo");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 69, -1, -1));

        txtPrefijo.setPreferredSize(new java.awt.Dimension(10, 20));
        getContentPane().add(txtPrefijo, new org.netbeans.lib.awtextra.AbsoluteConstraints(72, 66, 74, -1));
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 66, -1, -1));

        jLabel4.setText("Inicio");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 69, -1, -1));

        btnCancelarImprimible.setText("Cancelar");
        btnCancelarImprimible.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarImprimibleActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancelarImprimible, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnGuardarConsecutivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarConsecutivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarConsecutivoActionPerformed

    private void btnCancelarImprimibleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarImprimibleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarImprimibleActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModalNumeracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModalNumeracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModalNumeracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModalNumeracion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModalNumeracion dialog = new ModalNumeracion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnCancelarImprimible;
    public javax.swing.JButton btnGuardarConsecutivo;
    public javax.swing.JComboBox<String> cmbImprimible;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    public javax.swing.JSpinner spnConsecutivo;
    public javax.swing.JTextField txtPrefijo;
    // End of variables declaration//GEN-END:variables
}
